config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
  has_many :reviews, :dependent => :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, :inclusion => { :in => 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [ :show, :edit, :update, :destroy ]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class=container>

<h1>List of Restaurants:</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant)%></li>
  <% end %>
</ul>

<%= link_to "Create a new Restaurant", new_restaurant_path, class: "btn btn-primary"%>

</div>

app/views/restaurants/new.html.erb
<div class=container>
<h2>Create your new Restaurant</h1>

  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit "Create", class: "btn btn-primary"%>
    <%= link_to "Back to all restaurants", restaurants_path, class: "btn btn-dark"%>
  <% end %>

</div>

app/views/restaurants/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Name:</strong>
    <%= @restaurant.name %>
  </p>
  <p>
    <strong>Address:</strong>
    <%= @restaurant.address %>
  </p>
  <p>
    <strong>Phone Number:</strong>
    <%= @restaurant.phone_number %>
  </p>
  <p>
    <strong>Category:</strong>
    <%= @restaurant.category %>
  </p>

  <div class="container mt-4 text-center">
    <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn btn-warning" %>
    <%= link_to 'Back', restaurants_path, class: "btn btn-dark" %>
    <%= link_to 'Leave a review', new_restaurant_review_path(@restaurant), class: "btn btn-secondary" %>
  </div>
  <div class="container my-4">
    <ul class="list-group">
      <% @restaurant.reviews.each do |element| %>
        <li class="list-group-item my-2">
        <%= element.content %>
        <%= link_to "Remove",
        review_path(params[:id]),
        method: :delete,
        data: { confirm: "Are you sure?" },
        class: "btn btn-danger" %>
        </li>
      <% end %>
    </ul>
  </div>
</div

app/views/reviews/create.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <p><strong>Create a new Reviwe for: <%= @restaurant.name %></strong></p>

</div>

app/views/reviews/new.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <p><strong>CREATE A REVIEW FOR: <%= @restaurant.name %></strong></p>


  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Submit Review", class: "btn btn-primary justify-content-end" %>
  <% end %>

</div>